import { describe, it, expect } from 'bun:test';
import { runTransform } from './transform.js';



describe('compiled babel baseline for css/cssMap', () => {
  it('Should match inline snapshot for basic css usage', () => {
    const source = `
import { css } from '@compiled/react';

const buttonStyles = css({
  border: 'none',
  borderRadius: '3px',
  padding: '8px 10px',
  backgroundColor: '#6554C0',
  color: '#fff',
  fontWeight: 400,
  fontFamily: 'Arial',
  fontSize: '14px',

  '&:hover': {
    backgroundColor: '#8777D9',
  },

  '&:active': {
    backgroundColor: '#5243AA',
  },
});
<div css={buttonStyles} />
`;
    const { result } = runTransform(source, {
      isSource: true,
      extract: false,
      emitCode: true,
      config: {},
      filename: 'css-cssMap-basic.fixture.jsx',
    });

    const code = result && result.code;
    expect(code).toMatchInlineSnapshot(`
      "/* css-cssMap-basic.fixture.jsx generated by @compiled/babel-plugin v0.38.1 */
      import * as React from 'react';
      import { ax, ix, CC, CS } from "@compiled/react/runtime";
      const _11 = "._1di6vctu:active{background-color:#5243aa}";
      const _10 = "._irr3mlcl:hover{background-color:#8777d9}";
      const _1 = "._1wybdlk8{font-size:14px}";
      const _0 = "._ect41ttw{font-family:Arial}";
      const _9 = "._k48p1nn1{font-weight:400}";
      const _8 = "._syazu67f{color:#fff}";
      const _7 = "._bfhk1mzw{background-color:#6554c0}";
      const _6 = "._19bv19bv{padding-left:10px}";
      const _5 = "._n3tdftgi{padding-bottom:8px}";
      const _4 = "._u5f319bv{padding-right:10px}";
      const _3 = "._ca0qftgi{padding-top:8px}";
      const _2 = "._2rko1l7b{border-radius:3px}";
      const _ = "._19itglyw{border:none}";
      const buttonStyles = null;
      <CC>
        <CS>{[_, _2, _3, _4, _5, _6, _7, _8, _9, _0, _1, _10, _11]}</CS>
        {<div className={ax(["_19itglyw _2rko1l7b _ca0qftgi _u5f319bv _n3tdftgi _19bv19bv _bfhk1mzw _syazu67f _k48p1nn1 _ect41ttw _1wybdlk8 _irr3mlcl _1di6vctu"])} />}
      </CC>;"
    `)
 });
 it('Should match inline snapshot for cssMap usage', () => {
  const source = `
  
    import { css, cssMap } from '@compiled/react';
  const styles = css({
    color: 'red',
    '&:hover': { color: 'blue' },
  });
  const stylesMap = cssMap({
    primary: {
      color: 'red',
    },
    flyoutAnimateClosed: {
      display: 'none',
      '@media (min-width: 64rem)': {
        gridArea: 'main',
      },
      '@supports not (-moz-appearance: none)': {
        '@media (prefers-reduced-motion: no-preference)': {
          transitionProperty: 'transform, display',
          transitionDuration: '0.2s',
          transitionBehavior: 'allow-discrete',
          transform: 'translateX(-100%)',
        },
      },
    },
  });
   <div css={[styles, Math.random() > 0.5 && stylesMap.flyoutAnimateClosed]} />
  `
  const { result } = runTransform(source, {
    isSource: true,
    extract: false,
    emitCode: true,
    config: {},
    filename: 'css-cssMap-basic.fixture.jsx',
  });
  const code = result && result.code;
  expect(code).toMatchInlineSnapshot(`
    "/* css-cssMap-basic.fixture.jsx generated by @compiled/babel-plugin v0.38.1 */
    import * as React from 'react';
    import { ax, ix, CC, CS } from "@compiled/react/runtime";
    const _5 = "@supports not (-moz-appearance:none){@media (prefers-reduced-motion:no-preference){._139f8iot{transition-property:transform,display}._1tpvfnf5{transition-duration:.2s}._sylc1a5r{transition-behavior:allow-discrete}._1uwsjq3t{transform:translateX(-100%)}}}";
    const _4 = "@media (min-width:64rem){._qiln1gzg{grid-area:main}}";
    const _3 = "._1e0cglyw{display:none}";
    const _2 = "._30l313q2:hover{color:blue}";
    const _ = "._syaz5scu{color:red}";
    const styles = null;
    const stylesMap = {
      primary: "_syaz5scu",
      flyoutAnimateClosed: "_1e0cglyw _qiln1gzg _139f8iot _1tpvfnf5 _sylc1a5r _1uwsjq3t"
    };
    <CC>
      <CS>{[_, _2, _3, _4, _5]}</CS>
      {<div className={ax(["_syaz5scu _30l313q2", Math.random() > 0.5 && stylesMap.flyoutAnimateClosed])} />}
    </CC>;"
  `)
 });
 it('Should match inline snapshot for styled usage', () => {
  const source = `
    import { styled } from '@compiled/react';

    const Button = styled.div({
      color: 'red',
      '&:hover': { color: 'blue' },
    })

    const Btn = () => <Button />
     
  `
  const { result } = runTransform(source, {
    isSource: true,
    extract: false,
    emitCode: true,
    config: {},
    filename: 'css-cssMap-basic.fixture.jsx',
  });
  const code = result && result.code;
  expect(code).toMatchInlineSnapshot(`
    "/* css-cssMap-basic.fixture.jsx generated by @compiled/babel-plugin v0.38.1 */
    import { forwardRef } from 'react';
    import * as React from 'react';
    import { ax, ix, CC, CS } from "@compiled/react/runtime";
    const _2 = "._30l313q2:hover{color:blue}";
    const _ = "._syaz5scu{color:red}";
    const Button = forwardRef(({
      as: C = "div",
      style: __cmpls,
      ...__cmplp
    }, __cmplr) => {
      if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
      }
      return <CC>
            <CS>{[_, _2]}</CS>
            <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_syaz5scu _30l313q2", __cmplp.className])} />
          </CC>;
    });
    if (process.env.NODE_ENV !== 'production') {
      Button.displayName = 'Button';
    }
    const Btn = () => <Button />;"
  `)
 })
 it('Should match inline snapshot for styled usage with keyframes', () => {
  const source = `
	      import { css, keyframes } from '@compiled/react';
	      const moveFade = keyframes({
	        from: { opacity: 0 },
	        to: { opacity: 1 },
	      });
	      <div css={{ animationName: moveFade }} />
  `
  const { result } = runTransform(source, {
    isSource: true,
    extract: false,
    emitCode: true,
    config: {},
    filename: 'css-cssMap-basic.fixture.jsx',
  });
  const code = result && result.code;
  expect(code).toMatchInlineSnapshot(`
    "/* css-cssMap-basic.fixture.jsx generated by @compiled/babel-plugin v0.38.1 */
    import * as React from 'react';
    import { ax, ix, CC, CS } from "@compiled/react/runtime";
    const _2 = "._j7hq1wwu{animation-name:kgnpaw5}";
    const _ = "@keyframes kgnpaw5{0%{opacity:0}to{opacity:1}}";
    const moveFade = null;
    <CC>
      <CS>{[_, _2]}</CS>
      {<div className={ax(["_j7hq1wwu"])} />}
    </CC>;"
  `)
});
it('emits JSX for inline css object on element', () => {
  const source = `
    import { css } from '@compiled/react';
    <div css={{ color: 'blue' }} />
  `;
  const { result } = runTransform(source, {
    isSource: true,
    extract: false,
    emitCode: true,
    config: {},
    filename: 'jsx-inline-object.fixture.jsx',
  });
  const code = result && result.code;
  expect(code).toMatch(/className=\{ax\(\["_[a-z0-9]+"\]\)\}/);
});

it('emits JSX when css prop receives css() call', () => {
  const source = `
    import { css } from '@compiled/react';
    <div css={css({ color: 'blue' })} />
  `;
  const { result } = runTransform(source, {
    isSource: true,
    extract: false,
    emitCode: true,
    config: {},
    filename: 'jsx-css-call.fixture.jsx',
  });
  const code = result && result.code;
  expect(code).toMatch(/className=\{ax\(\["_[a-z0-9]+"\]\)\}/);
});

it('merges template literal css with existing className via cx', () => {
  const source = `
    import { css } from '@compiled/react';
    <div css={\`color: blue\`} className={cx("A", "B")} />
  `;
  const { result } = runTransform(source, {
    isSource: true,
    extract: false,
    emitCode: true,
    config: {},
    filename: 'jsx-template-cx.fixture.jsx',
  });
  const code = result && result.code;
  expect(code).toMatch(/className=\{ax\(\["_[a-z0-9]+",\s*cx\("A",\s*"B"\)\]\)\}/);
});

it('emits JSX when css prop receives cssMap variants in arrays and conditionals', () => {
  const source = `
    import { css, cssMap } from '@compiled/react';
    const isActive = true;
    const count = 1;
    const themes = cssMap({
      primary: { color: 'red', '&:hover': { color: 'blue' } },
      secondary: { backgroundColor: '#eee' },
      danger: { color: 'crimson' },
    });
    <>
      <div css={themes.primary} />
      <div css={[themes.primary, isActive && themes.secondary]} />
      <div css={[false && themes.secondary, themes.primary]} className={cx('A')} />
      <div css={[themes.secondary, themes.danger, count > 0 && themes.primary]} />
    </>
  `;
  const { result } = runTransform(source, {
    isSource: true,
    extract: false,
    emitCode: true,
    config: {},
    filename: 'css-map-jsx.fixture.jsx',
  });
  const code = result && result.code;
  // Should emit 4 className=ax([...]) occurrences
  const matches = code && code.match(/className=\{ax\(\[/g);
  expect(matches && matches.length).toBe(4);
  // First should be a simple single element array
  expect(code).toMatch(/<div className=\{ax\(\[[^\]]+\]\)\} \/>/);
  // Should preserve conditional and existing className merging via cx
  expect(code).toMatch(/className=\{ax\(\[[^\]]+,\s*cx\('A'\)\]\)\}/);
});
})



